version: '2.3'

services:
  notebook:
    image: "deeplabcut-work-image:2.0.5"
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - /mnt/:/mnt/
        #      - /home/pipeline_data/:/tmp/
        #      - $HOME/Documents/pipeline/:/data/pipeline/
        #      - .:/data/DeepLabCut
      - /home/donnie/Documents/Repos/DeepLabCut:/work/
      - /home/donnie/Documents/Repos/DLC_tool_DK:/work/
    env_file: .env
    working_dir: /work/
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      - jupyter 
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=''
      - --no-browser
  
  bash:
    image: "deeplabcut-work-image:2.0.5"
    runtime: nvidia
    volumes:
      - /mnt/:/mnt/
        #      - /home/pipeline_data/:/tmp/
        #        - /home/pipeline_data/:/mnt/data/
        #      - $HOME/Documents/pipeline/:/data/pipeline/
        #      - .:/data/DeepLabCut
      - /home/donnie/Documents/Repos/DeepLabCut:/work/
      - /home/donnie/Documents/Repos/DLC_tool_DK:/work/
    env_file: .env
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
      - USER_HOME=/DeepLabCut
    env_file: .env
    entrypoint:
      - /bin/bash
